### ISSUE TITLE
Question regrads to the rule

### ISSUE THREAD

**Issue by zilunzhang** [IBM/cdfsl-benchmark#10]
Hi, I have a question regards to the competition rule.

For the transductive setting, do we allow to use intra-class relationships for data?  For example, if we have a similarity matrix (shape 100 * 100 in 5way-5shot-15query setting, 5*(5+15) ) and we want to initialize it, can we assume the entry for queries from the same class to have similarity 1? That is, we don't know the current query belongs to which class, but we do know it belongs to the same class with some other query.

Thanks!

**Comment by zilunzhang** [comment]
![ex](https://user-images.githubusercontent.com/22264060/78007964-96fec880-7371-11ea-91c4-8f0f6fe14cb4.jpeg)

**Comment by yunhuiguo** [comment]
Hi @zilunzhang, this is not allowed. You can not assume that you already know if the query images are belongs to the same class.

**Comment by zilunzhang** [comment]
> Hi @zilunzhang, this is not allowed. You can not assume that you already know if the query images are belongs to the same class.

Sure, thanks.
