### ISSUE TITLE
GPUs for 5-way 50-shot

### ISSUE THREAD

**Issue by chrisyxue** [IBM/cdfsl-benchmark#11]
Hi, could you please tell us how many GPUs we need to train a few-shot model (Res-12+any classifier) in the setting of 5-way 50-shot. Also, is it necessary？ I mean, 50 samples may not be considered as "few-shot"

**Comment by yunhuiguo** [comment]
@christo4ferris One GPU with 12189MiB is enough.

**Comment by chrisyxue** [comment]
OK. Thank you for letting me know that.
