### ISSUE TITLE
RAM utilization

### ISSUE THREAD

**Issue by johncai117** [IBM/cdfsl-benchmark#12]
Hi,

I was wondering why the code seems to have the RAM blowing up (>25 Gb) in the data loading process. Do we need to force the code to utilise disk space as RAM if our RAM size limit is 25 Gb?

Thanks.

**Comment by billcai** [comment]
```Traceback (most recent call last):
  File "./train.py", line 115, in <module>
    model = train(base_loader, model, optimization, start_epoch, stop_epoch, params)
  File "./train.py", line 29, in train
    model.train_loop(epoch, base_loader,  optimizer ) 
  File "/project/cdfsl-benchmark-master/methods/baselinetrain.py", line 46, in train_loop
    for i, (x,y) in enumerate(train_loader):
  File "/.local/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 501, in __iter__
    return _DataLoaderIter(self)
  File "/.local/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 289, in __init__
    w.start()
  File "/usr/lib/python3.6/multiprocessing/process.py", line 105, in start
    self._popen = self._Popen(self)
  File "/usr/lib/python3.6/multiprocessing/context.py", line 223, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "/usr/lib/python3.6/multiprocessing/context.py", line 277, in _Popen
    return Popen(process_obj)
  File "/usr/lib/python3.6/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/usr/lib/python3.6/multiprocessing/popen_fork.py", line 66, in _launch
    self.pid = os.fork()
OSError: [Errno 12] Cannot allocate memory
```

Facing a similar issue. It looks like the multiprocessing fork is requiring a lot of memory. Tested this with a 32GB machine, with batch size 1 and workers 1.

**Comment by Ze-Yang** [comment]
also face the same problem

**Comment by yunhuiguo** [comment]
@johncai117 @billcai @Ze-Yang , do you still have the problem? Can you give more details (number of shots, ...) about the problem? Thanks!

**Comment by johncai117** [comment]
I downsampled the images to 75% and now I have enough RAM for the dataloader

**Comment by zilunzhang** [comment]
The problem is in line 59 of miniImageNet_few_shot.py (and other dataset files).

I solved the problem by changing the appended PIL image class to its file path (str class) and read the file from the path during iteration (revised __getitem__ in SubDataset class). It only takes a few seconds and very little RAM space to finish the io in the beginning (It used to take more than 100GB RAM).

**Comment by Veagau** [comment]
``

> The problem is in line 59 of miniImageNet_few_shot.py (and other dataset files).
> 
> I solved the problem by changing the appended PIL image class to its file path (str class) and read the file from the path during iteration (revised **getitem** in SubDataset class). It only takes a few seconds and very little RAM space to finish the io in the beginning (It used to take more than 100GB RAM).

I find that the process of data loading is slow too, could you please share your modified code.

**Comment by siyang-jiang** [comment]
> The problem is in line 59 of miniImageNet_few_shot.py (and other dataset files).
> 
> I solved the problem by changing the appended PIL image class to its file path (str class) and read the file from the path during iteration (revised **getitem** in SubDataset class). It only takes a few seconds and very little RAM space to finish the io in the beginning (It used to take more than 100GB RAM).

Yep! Do not cache all data in RAM... IBM is rich ( with large memory, Lol), but in our machine, this is not a suitable way for us...
