### ISSUE TITLE
Question about Meta Learning architecture that used in the paper.

### ISSUE THREAD

**Issue by whoamibro** [IBM/cdfsl-benchmark#14]
Hello, I saw that you use Relation Net as one of the comparison models for your method.

In the paper you use ResNet10 for the backbone of Relation Net encoder, however there's no information about relation module. 

Can I get the configuration of the relation module that you used for your experiment?

**Comment by yunhuiguo** [comment]
@whoamibro , the relation module is the same as https://github.com/wyharveychen/CloserLookFewShot/blob/master/methods/relationnet.py
