### ISSUE TITLE
Is each query image independent or not?

### ISSUE THREAD

**Issue by jiafongyeh** [IBM/cdfsl-benchmark#15]
Hi @yunhuiguo,

Is it allowed to have any operation between query images if we make sure there is no assumption about their class? (distance calculation  etc.)
Or should we keep the query images being independent too?

If we can have those operations, is it allowed to check the predicted class of query images from our model? (e.g. when predicting the second query image, can we check the predicted class of the first images?  we won't assume the number of the query images predicted to each class should be same.)

Thank you!

**Comment by yunhuiguo** [comment]
Hi @JiaFong, this is not allowed. For query images you should treat them as independent samples from the domain distribution.

**Comment by jiafongyeh** [comment]
Ok, thank you for the quick reply.
