### ISSUE TITLE
Question about the arXiv paper

### ISSUE THREAD

**Issue by jiafongyeh** [IBM/cdfsl-benchmark#16]
Hi @yunhuiguo,

sorry, I have one more question about the arXiv paper.

Since we can't finish our paper before your workshop deadline, so we will put it on arXiv as the rule required.
I would like to know is it available to submit the arXiv paper to other conferences? (if the conference accepts an arXiv submission).

We will extend the paper with extra experiments, but most of the content will be the same as the arXiv paper. 

Thank you for your help.

**Comment by yunhuiguo** [comment]
Hi @JiaFong, you can submit the paper for the challenge to other conferences :).

**Comment by jiafongyeh** [comment]
Thank you so much :)
