### ISSUE TITLE
Evaluation episodes

### ISSUE THREAD

**Issue by carmete** [IBM/cdfsl-benchmark#21]
On the challenge website it states: "For each  evaluation, the same 600 randomly sampled few-shot episodes should be used for consistency, ... .  Participants must employ the supplied code in order to conduct their evaluations." (https://www.learning-with-limited-labels.com/challenge#h.p_h74e3HJnMMqn)

As far as I can see, the the supplied code in `finetune.py`, does not guarantee, that always the same 600 episodes will be sampled. The only control over randomness is line 164 `np.random.seed(10)`, but this does not seem to be enough.

Could you please clarify, if one should use this exact code or if one should instead take additional measures to guarantee, that always the same 600 episodes will be sampled?

Thank you for your help!

**Comment by yunhuiguo** [comment]
Hi @carmete ,  it is ok to just randomly sample 600 episodes.

**Comment by carmete** [comment]
Awesome, thank you!
