### ISSUE TITLE
Question about arxiv link

### ISSUE THREAD

**Issue by leezhp1994** [IBM/cdfsl-benchmark#25]
Hi, 
Submitting the paper on arxiv takes a while to get the arxiv link. And our current state on arxiv is _on hold_. I'm afraid we won't be able to get the link by the deadline. 
So if we don't get the arxiv link by the deadline, can we just upload the PDF of our paper on CMT3?

**Comment by Zhen-ao** [comment]
> Hi,
> Submitting the paper on arxiv takes a while to get the arxiv link. And our current state on arxiv is _on hold_. I'm afraid we won't be able to get the link by the deadline.
> So if we don't get the arxiv link by the deadline, can we just upload the PDF of our paper on CMT3?

I have the same question

**Comment by yunhuiguo** [comment]
@123zhen123 @leezhp1994 It is fine to just upload the PDF of the paper on CMT if you don't get the link. The field now is optional.
