### ISSUE TITLE
Implicit transduction learning

### ISSUE THREAD

**Issue by jiafongyeh** [IBM/cdfsl-benchmark#26]
I would like to check implicit transduction learning is allowed to used in Track 1 or not?
We followed the instructions in your paper and other issues.
For the current setting, we use implicit transduction learning in our result for Track 1.

https://github.com/IBM/cdfsl-benchmark/issues/2
https://github.com/IBM/cdfsl-benchmark/issues/8

But, I just noticed that in issue 22, you mention that the query samples are not predicted independently if applying implicit transduction learning.

So it's forbidden in Track 1?
We may not have enough time to change the result now...

**Comment by yunhuiguo** [comment]
Hi @JiaFong , it is fine for track 1. For track 2, the theme is to use additional unlabeled data for un/self/semi-supervised learning.

**Comment by jiafongyeh** [comment]
Ok, thank you for quick reply.
I really appreciate it.
