### ISSUE TITLE
unable to reproduce the result in the paper

### ISSUE THREAD

**Issue by SarahQiong** [IBM/cdfsl-benchmark#29]
Hi, I want to reproduce the result in Table 1 in your paper with Protonet provided in your code. But I  am not able to reproduce the result. The 5-way 5-shot classification accuracy I can get is 69.23 +- 0.75, which is also 10% lower than reported. Any suggestion?

**Comment by yunhuiguo** [comment]
@SarahQiong Have you resolved the issue?
