### ISSUE TITLE
Easier way to setup Chest X-rays?

### ISSUE THREAD

**Issue by CSer-Tang-hao** [IBM/cdfsl-benchmark#3]
The current way requires to downloading the entire NIH Chest X-ray Dataset of 42GB...This will not be easy in China. o(╥﹏╥)o
We can infer from the "./datasets/Chest?_few_shot.py" file that not all the images in this dataset need to be used, so can you provide a simplified version of the dataset and annotations with a google drive link?

**Comment by CSer-Tang-hao** [comment]
We also have an issue that we couldn't run the "Chest_few_shot.py" successfully although we had downloaded the full dataset. After upzip the data.zip, we found that there were 12 folders containing "images" which are "image_001~012".  Just "ChestX_path+"/images/" in the "Chest_few_shot.py". We are very puzzled and hope to get a reply as soon as possible.

**Comment by yunhuiguo** [comment]
> We also have an issue that we couldn't run the "Chest_few_shot.py" successfully although we had downloaded the full dataset. After upzip the data.zip, we found that there were 12 folders containing "images" which are "image_001~012". Just "ChestX_path+"/images/" in the "Chest_few_shot.py". We are very puzzled and hope to get a reply as soon as possible.

Hi @CSer-Tang-hao, please create a directory called "ChestX_path+"/images/" and move all the images under  "image_001~012" to this directory.
