### ISSUE TITLE
Question about the pre-trained data?

### ISSUE THREAD

**Issue by ztf-ucas** [IBM/cdfsl-benchmark#32]
Is the model pre-trained on the entire miniImageNet (100 classes) or on the meta-training set (64 base classes)? 
Besides, why the parameter --num_classes is 200 in io_utils.py?
Thank you very much!

**Comment by yunhuiguo** [comment]
Hi @ztf-ucas , the model is pre-trained on the meta-training set (64 base classes). For --num_classes=200, you can ignore it if you do not use that parameter.
