### ISSUE TITLE
Some question about this project.

### ISSUE THREAD

**Issue by WHQ1111** [IBM/cdfsl-benchmark#34]
I have some question about this challenge:

1) In the setting that we use miniImageNet as the source domain and use CropDiseases, EuroSAT, ISIC2018 and ChestX as the target domains, if we use the base classes (64) of the miniImageNet as the training classes, which classes do we use as the validation classes and do we use all classes in the target domain as test classes?

2) As we can see, ImageNet data (155G) needs to be downloaded to construct the miniImageNet dataset. So can we use a simpler way, just like in [CrossDomainFewShot](https://github.com/hytseng0509/CrossDomainFewShot).

3. Can you provide data processing scripts for the four datasets: CropDiseases, EuroSAT, ISIC2018 and ChestX? I only saw the ones of miniImageNet and CUB datasets?

**Comment by yunhuiguo** [comment]
Hi @WHQ1111,

1. For the validation classes, you can use the validation classes of miniImageNet. You can also use other datasets but not the evaluation datasets. Yeah, all classes in the target domain should be used as test classes.

2. There is no need to download the whole ImageNet. The provided link will only donwload miniImageNet .

3. The data processing scripts for the four datasets are in the datasets folder.

**Comment by WHQ1111** [comment]
> Hi @WHQ1111,
> 
> 1. For the validation classes, you can use the validation classes of miniImageNet. You can also use other datasets but not the evaluation datasets. Yeah, all classes in the target domain should be used as test classes.
> 2. There is no need to download the whole ImageNet. The provided link will only donwload miniImageNet .
> 3. The data processing scripts for the four datasets are in the datasets folder.

Thank you very much. Actually, I have another question about the ISIC dataset. As we can see, there are many datasets (Task 1,2,3) in [ISIC2028](https://challenge.isic-archive.com/data#2018), which ones should we download and how we process them (unzip, etc.)?

**Comment by yunhuiguo** [comment]
@WHQ1111  task 3. Should just unzip.
