### ISSUE TITLE
Some questions about this challenge

### ISSUE THREAD

**Issue by WHQ1111** [IBM/cdfsl-benchmark#35]
With such large domain differences (miniImageNet-->Chest-X), does domain generation make sense?  Will there be such a big domain difference in the real world? In this case there seems to be no valuable information that can be transfered from the source domain to the target domain.

**Comment by yunhuiguo** [comment]
Hi @WHQ1111 , I personally think domain generation can be a good idea, such as 'interpolating' between the two domains. For transferring between "miniImageNet-->Chest-X", there are some papers on transferring from ImageNet to medical images, such as https://papers.nips.cc/paper/8596-transfusion-understanding-transfer-learning-for-medical-imaging.pdf.
