### ISSUE TITLE
Questions about the rules

### ISSUE THREAD

**Issue by XiSHEN0220** [IBM/cdfsl-benchmark#5]
Hi, thanks for organizing the challenge!!

We have several questions about the rules: 
1. Are we allowed to use ImageNet validation or test set? 
2. We should only use ResNet-10 as the backbone? 
3. Do we need to respect the preprocessing in the provided code? especially the resolution of images? (many academic papers working on lower resolution)

Thanks and looking forward to your reply.

**Comment by yunhuiguo** [comment]
Hi @XiSHEN0220,

1. Only miniImageNet is allowed as provided in the competition. To be fair for all the participants, no other sources are allowed. 
2. Any backbone is fine.
3. Any resolution is fine. And you can also modify the data preprocessing steps.

**Comment by XiSHEN0220** [comment]
Thanks for your reply!!!
