### ISSUE TITLE
Question about cdfsl challenge

### ISSUE THREAD

**Issue by jjn037** [IBM/cdfsl-benchmark#7]
Hello! Can we use unlabeled target data to train our model?

**Comment by yunhuiguo** [comment]
Hi @jjn037, there will be a second track which allows to use unlabeled target data for training. The second track will be announced soon, so stay tuned. For the current track, it is not allowed to use unlabeled target data.

**Comment by yunhuiguo** [comment]
@jjn037 Please see the challenge website for the update.
