### ISSUE TITLE
Question about cdfsl challenge

### ISSUE THREAD

**Issue by lynlynlyn96** [IBM/cdfsl-benchmark#8]
1. Can we use own processing of datasets, i.e., normalizing the size of all picture in a dataset and packaging it into a large tensor for storage.          

2.  Can Transductive Inference [1] be used in track 1?  Or is implicit transduction learning (i.e., MAML uses batchnorm to share information in test inference) OK.

[1] Transductive Episodic-Wise Adaptive Metric for Few-Shot Learning, ICCV2019

**Comment by yunhuiguo** [comment]
@lynlynlyn96  Both 1 and 2 are fine.

**Comment by lynlynlyn96** [comment]
Thank you. Does this mean that 15 query samples of each category can be used for unsupervised training in each episode.

**Comment by yunhuiguo** [comment]
Yes. The 15 query samples of each category are at your disposal.
